/**:
  ros__parameters:
    camera_info_url: package://rm_bringup/config/camera_info.yaml
    path: "/root/Robomaster/hfut_rm_auto_aim_ws/resources/output2.avi"
    frame_rate: 60
    start_frame: 0
    frame_id: "camera_optical_frame"
    keep_looping: true              #是否循环播放
