image_width: 640
image_height: 480
camera_name: blind_camera_2
camera_matrix:
  rows: 3
  cols: 3
  data: [480.57616,   0.     , 249.42098,
           0.     , 480.78328, 161.8316 ,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.141303, -0.123992, 0.000657, 0.000725, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [500.16098,   0.     , 249.82295,   0.     ,
           0.     , 500.53125, 162.16717,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
