# 6mm hik 相机

# image_width: 1440
# image_height: 1080
# camera_name: narrow_stereo
# camera_matrix:
#   rows: 3
#   cols: 3
#   data: [2400.01253, 0.0, 681.48605,
#          0.0, 2399.71940, 503.99776,
#          0.0, 0.0, 1.0]
# distortion_model: plumb_bob
# distortion_coefficients:
#   rows: 1
#   cols: 5
#   data: [-0.04497521, 0.25307794, -0.00070048, 0.00058114, 0.0]
# rectification_matrix:
#   rows: 3
#   cols: 3
#   data: [1.0, 0.0, 0.0,
#          0.0, 1.0, 0.0,
#          0.0, 0.0, 1.0]
# projection_matrix:
#   rows: 3
#   cols: 4
#   data: [2395.74438, 0.0, 681.60749, 0.0,
#          0.0, 2395.83374, 503.22432, 0.0,
#          0.0, 0.0, 1.0, 0.0]

# 16mm hik 相机

image_width: 1440
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [4504.76723,    0.     ,  772.01116,
            0.     , 4505.17531,  589.76715,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.051808, -2.629005, 0.002191, 0.000449, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [4499.64258,    0.     ,  771.85685,    0.     ,
            0.     , 4501.18506,  589.69534,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]

