# image_width: 1280
# image_height: 1024
# camera_name: narrow_stereo
# camera_matrix:
#   rows: 3
#   cols: 3
#   data: [3063.82412,    0.     ,  688.86289,
#             0.     , 3050.91074,  512.3856 ,
#             0.     ,    0.     ,    1.     ]
# distortion_model: plumb_bob
# distortion_coefficients:
#   rows: 1
#   cols: 5
#   data: [-0.088070, 0.944094, -0.001709, 0.003968, 0.000000]
# rectification_matrix:
#   rows: 3
#   cols: 3
#   data: [1., 0., 0.,
#          0., 1., 0.,
#          0., 0., 1.]
# projection_matrix:
#   rows: 3
#   cols: 4
#   data: [3060.18069,    0.     ,  690.57197,    0.     ,
#             0.     , 3050.28904,  511.7533 ,    0.     ,
#             0.     ,    0.     ,    1.     ,    0.     ]

# image_width: 1440
# image_height: 1080
# camera_name: narrow_stereo
# camera_matrix:
#   rows: 3
#   cols: 3
#   data: [1795.48075,    0.     ,  719.15967,
#             0.     , 1788.97397,  554.12545,
#             0.     ,    0.     ,    1.     ]
# distortion_model: plumb_bob
# distortion_coefficients:
#   rows: 1
#   cols: 5
#   data: [-0.073464, 0.128799, 0.001334, 0.001541, 0.000000]
# rectification_matrix:
#   rows: 3
#   cols: 3
#   data: [1., 0., 0.,
#          0., 1., 0.,
#          0., 0., 1.]
# projection_matrix:
#   rows: 3
#   cols: 4
#   data: [1780.16607,    0.     ,  720.53861,    0.     ,
#             0.     , 1778.69562,  554.92559,    0.     ,
#             0.     ,    0.     ,    1.     ,    0.     ]


# image_width: 1280
# image_height: 1024
# camera_name: narrow_stereo
# camera_matrix:
#   rows: 3
#   cols: 3
#   data: [3013.59201,    0.     ,  607.78709,
#             0.     , 3012.58017,  504.08045,
#             0.     ,    0.     ,    1.     ]
# distortion_model: plumb_bob
# distortion_coefficients:
#   rows: 1
#   cols: 5
#   data: [-0.109005, 1.057312, -0.000786, -0.000327, 0.000000]
# rectification_matrix:
#   rows: 3
#   cols: 3
#   data: [1., 0., 0.,
#          0., 1., 0.,
#          0., 0., 1.]
# projection_matrix:
#   rows: 3
#   cols: 4
#   data: [3005.13818,    0.     ,  607.28611,    0.     ,
#             0.     , 3003.10791,  503.29285,    0.     ,
#             0.     ,    0.     ,    1.     ,    0.     ]

image_width: 1280
image_height: 1024
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [3000.66453,    0.     ,  696.28255,
            0.     , 3003.37478,  518.33017,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.038092, -0.056591, 0.000185, 0.001304, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2992.14697,    0.     ,  696.49421,    0.     ,
            0.     , 2997.08179,  517.88869,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
