profile:
  image_source: video
  serial_mode: virtual
  detector_type: armor_detector
  composition: standalone
  auto_buff: "off"
  debug: "on"
  namespace: ""
  odom2camera:
    xyz: "0.151 0.000 0.040"
    rpy: "0.000 0.000 0.000"
