video_player:
  ros__parameters:
    video_path: "package://rm_bringup/config/video_test/input.mp4"
    loop_playback: true
    fps: 120.0
    camera_name: camera
    frame_id: camera_optical_frame
    flip_image: false
    image_topic: image_raw
    use_sensor_data_qos: true
    camera_info_url: "package://rm_bringup/config/leg/camera_info.yaml"
